# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3.13

repos:
  # General fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: debug-statements
      - id: check-ast

  # Python code formatting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      # Run the linter with fixes (matching CI but with auto-fix)
      - id: ruff
        name: ruff lint with auto-fix
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi]
        files: ^(src|tests)/
      # Run the formatter
      - id: ruff-format
        types_or: [python, pyi]
        files: ^(src|tests)/

  # Type checking with mypy (matching CI)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        name: mypy type checking
        args: [--show-error-codes, --pretty, src/]
        files: ^src/
        pass_filenames: false
        additional_dependencies:
          - pydantic
          - pydantic-settings
          - httpx
          - pytest
          - pytest-asyncio
          - playwright
          - types-requests
          - types-beautifulsoup4
          - beautifulsoup4
          - lxml-stubs
          - types-PyYAML
          - structlog
          - click
          - rich

  # GitHub Actions workflow linting
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint-docker
        args: [-color]
        files: '^\.github/workflows/.*\.ya?ml$'

# Configuration for specific hooks
exclude: |
  (?x)^(
    .*\.egg-info/.*|
    \.git/.*|
    \.mypy_cache/.*|
    \.pytest_cache/.*|
    \.ruff_cache/.*|
    \.venv/.*|
    _build/.*|
    build/.*|
    dist/.*|
    node_modules/.*|
    venv/.*|
    htmlcov/.*|
    docs/_build/.*|
    __pycache__/.*|
    \.coverage|
    coverage\.xml|
    uv\.lock
  )$
