# YAML Linting Configuration
extends: default

rules:
  line-length:
    max: 120
    level: warning

  truthy:
    allowed-values: ['true', 'false']
    check-keys: false

  comments:
    min-spaces-from-content: 2

  comments-indentation: enable

  document-start:
    present: false

  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  brackets:
    max-spaces-inside: 1

  braces:
    max-spaces-inside: 1

  colons:
    max-spaces-after: 1

  commas:
    max-spaces-after: 1

  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  key-duplicates: enable

  new-line-at-end-of-file: enable

  trailing-spaces: enable

ignore: |
  .venv/
  venv/
  node_modules/
  .git/
  uv.lock
