site_name: Scrap-E Documentation
site_description: Universal data scraper for Web, APIs, databases, and files
site_author: Scrap-E Team
site_url: https://beelzer.github.io/scrap-e/

repo_name: beelzer/scrap-e
repo_url: https://github.com/beelzer/scrap-e
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_object_full_path: false
            show_category_heading: true
            docstring_style: google
            docstring_section_style: table
            merge_init_into_class: true
            filters: ["!^_"]

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
      - Configuration: getting-started/configuration.md
  - User Guide:
      - Web Scraping: user-guide/web-scraping.md
      - API Scraping: user-guide/api-scraping.md
      - Database Scraping: user-guide/database-scraping.md
      - File Processing: user-guide/file-processing.md
      - CLI Usage: user-guide/cli-usage.md
      - Error Handling: user-guide/error-handling.md
  - API Reference:
      - Core:
          - Base Scraper: api/core/base-scraper.md
          - Configuration: api/core/configuration.md
          - Models: api/core/models.md
          - Exceptions: api/core/exceptions.md
      - Scrapers:
          - HTTP Scraper: api/scrapers/http-scraper.md
          - Browser Scraper: api/scrapers/browser-scraper.md
          - API Scrapers: api/scrapers/api-scrapers.md
      - Parsers:
          - HTML Parser: api/parsers/html-parser.md
      - CLI:
          - Commands: api/cli/commands.md
  - Contributing: contributing.md
  - Development:
      - Pre-commit Hooks: pre-commit.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/beelzer/scrap-e
  version:
    provider: mike

copyright: Copyright &copy; 2024 Scrap-E Team
