name: "Install Dependencies"
description: "Install project dependencies using uv"
inputs:
  extras:
    description: 'Comma-separated list of extras to install (e.g., "dev,docs")'
    required: false
    default: ""
  install-playwright:
    description: "Whether to install Playwright browsers"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Install project dependencies
      run: |
        if [ -z "${{ inputs.extras }}" ]; then
          echo "Installing base dependencies..."
          uv sync
        else
          echo "Installing with extras: ${{ inputs.extras }}"
          # Special handling for 'dev' which means all dev dependencies
          if [ "${{ inputs.extras }}" = "dev" ]; then
            echo "Installing all dev dependencies..."
            uv sync --extra dev
          else
            # Convert comma-separated extras to multiple --extra flags
            EXTRAS_FLAGS=""
            IFS=',' read -ra EXTRAS <<< "${{ inputs.extras }}"
            for extra in "${EXTRAS[@]}"; do
              EXTRAS_FLAGS="$EXTRAS_FLAGS --extra $extra"
            done
            uv sync $EXTRAS_FLAGS
          fi
        fi
      shell: bash

    - name: Install Playwright browsers
      if: inputs.install-playwright == 'true'
      run: |
        echo "Installing Playwright browsers..."
        uv run playwright install --with-deps chromium firefox
      shell: bash

    - name: Show installed packages
      run: |
        echo "Installed packages:"
        uv pip list
      shell: bash
