blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/beelzer/scrap-e/wiki
    about: Please check the documentation first
  - name: Community Support
    url: https://github.com/beelzer/scrap-e/discussions
    about: Please ask and answer questions here
  - name: Security Issues
    url: https://github.com/beelzer/scrap-e/security/policy
    about: Please report security vulnerabilities here
