name: 'Setup Python Environment'
description: 'Sets up Python with uv package manager and caching'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'
  uv-version:
    description: 'uv version to install'
    required: false
    default: '0.5.0'
  cache-key-suffix:
    description: 'Additional cache key suffix'
    required: false
    default: ''

outputs:
  python-version:
    description: 'The installed Python version'
    value: ${{ steps.python-info.outputs.version }}
  python-location:
    description: 'The installed Python location'
    value: ${{ steps.python-info.outputs.location }}
  uv-version:
    description: 'The installed uv version'
    value: ${{ steps.uv-info.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv package manager
      uses: astral-sh/setup-uv@v6
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: true
        cache-dependency-glob: |
          **/pyproject.toml
          **/uv.lock
        cache-suffix: ${{ inputs.cache-key-suffix }}

    - name: Get Python info
      id: python-info
      shell: bash
      run: |
        set -euo pipefail
        echo "version=$(python --version | cut -d' ' -f2)" >> "$GITHUB_OUTPUT"
        echo "location=$(which python)" >> "$GITHUB_OUTPUT"

    - name: Get uv info
      id: uv-info
      shell: bash
      run: |
        set -euo pipefail
        echo "version=$(uv --version | cut -d' ' -f2)" >> "$GITHUB_OUTPUT"
