name: 'Setup Python with uv'
description: 'Set up Python environment using uv package manager'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6.6.0
      with:
        enable-cache: true
        cache-dependency-glob: 'uv.lock'

    - name: Set up Python
      run: uv python install ${{ inputs.python-version }}
      shell: bash

    - name: Verify Python installation
      run: |
        echo "Python location: $(which python)"
        echo "Python version: $(python --version)"
        echo "uv version: $(uv --version)"
      shell: bash
