name: 'Run Linting'
description: 'Run code quality checks with ruff and mypy'
inputs:
  run-ruff:
    description: 'Run ruff linter'
    required: false
    default: 'true'
  run-mypy:
    description: 'Run mypy type checker'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Run ruff linter
      if: inputs.run-ruff == 'true'
      run: |
        echo "Running ruff linter..."
        uv run ruff check src/ tests/ --output-format=github
      shell: bash
      
    - name: Run ruff formatter check
      if: inputs.run-ruff == 'true'
      run: |
        echo "Checking code formatting with ruff..."
        uv run ruff format src/ tests/ --check --diff
      shell: bash
      
    - name: Run mypy type checker
      if: inputs.run-mypy == 'true'
      run: |
        echo "Running mypy type checker..."
        uv run mypy src/
      shell: bash
      continue-on-error: true  # Type checking failures shouldn't block CI initially